name = "mc-server"
mc_version = "1.21"

[jar]
type = "fabric"
loader = "latest"
installer = "latest"

# Mods

## Base/Libraries
[[mods]]
type = "modrinth"
id = "fabric-api"

[[mods]]
type = "modrinth"
id = "cloth-config"

[[mods]]
type = "modrinth"
id = "collective"

[[mods]]
type = "modrinth"
id = "fabric-language-kotlin"

[[mods]]
type = "modrinth"
id = "puzzles-lib"

[[mods]]
type = "modrinth"
id = "forge-config-api-port"

[[mods]]
type = "modrinth"
id = "mru"

[[mods]]
type = "modrinth"
id = "owo-lib"

[[mods]]
type = "modrinth"
id = "craterlib"

## Optimization/Stability
[[mods]]
type = "modrinth"
id = "lithium"

[[mods]]
type = "modrinth"
id = "ferrite-core"

[[mods]]
type = "modrinth"
id = "modernfix"

[[mods]]
type = "modrinth"
id = "krypton"

[[mods]]
type = "modrinth"
id = "debugify"

[[mods]]
type = "modrinth"
id = "c2me-fabric"

[[mods]]
type = "modrinth"
id = "lmd"

[[mods]]
type = "modrinth"
id = "noisium"

[[mods]]
type = "modrinth"
id = "servercore"

[[mods]]
type = "modrinth"
id = "alternate-current"

[[mods]]
type = "modrinth"
id = "ksyxis"

[[mods]]
type = "modrinth"
id = "faster-random"

[[mods]]
type = "modrinth"
id = "railoptimization"

[[mods]]
type = "modrinth"
id = "scalablelux"

[[mods]]
type = "modrinth"
id = "neruina"

[[mods]]
type = "modrinth"
id = "threadtweak"

[[mods]]
type = "modrinth"
id = "vmp-fabric"

## Admin tools
[[mods]]
type = "modrinth"
id = "chunky"

[[mods]]
type = "modrinth"
id = "banhammer"

[[mods]]
type = "modrinth"
id = "image2map"

[[mods]]
type = "modrinth"
id = "invview"

[[mods]]
type = "modrinth"
id = "jline4mcdsrv"

[[mods]]
type = "modrinth"
id = "ledger"

[[mods]]
type = "modrinth"
id = "luckperms"

[[mods]]
type = "modrinth"
id = "mods-command"

[[mods]]
type = "modrinth"
id = "spark"

[[mods]]
type = "modrinth"
id = "deathlog"

[[mods]]
type = "modrinth"
id = "stackdeobf"

[[mods]]
type = "modrinth"
id = "vanish"

## Technical/Networking
[[mods]]
type = "modrinth"
id = "floodgate"

[[mods]]
type = "modrinth"
id = "geyser"

[[mods]]
type = "modrinth"
id = "dcintegration"

[[mods]]
type = "modrinth"
id = "hurricane"

[[mods]]
type = "modrinth"
id = "bluemap"

[[mods]]
type = "modrinth"
id = "viafabric"

[[mods]]
type = "modrinth"
id = "no-chat-reports"

## Compatibility
[[mods]]
type = "modrinth"
id = "servux"

[[mods]]
type = "modrinth"
id = "jade"

## Commands
[[mods]]
type = "modrinth"
id = "compact-help-command"

[[mods]]
type = "modrinth"
id = "coord-finder"

[[mods]]
type = "modrinth"
id = "wits"

[[mods]]
type = "modrinth"
id = "helpfulcommands"

## Gamplay/Features
[[mods]]
type = "modrinth"
id = "healing-campfire"

[[mods]]
type = "modrinth"
id = "conduits-prevent-drowned"

[[mods]]
type = "modrinth"
id = "anvil-restoration"

[[mods]]
type = "modrinth"
id = "zombify"

[[mods]]
type = "modrinth"
id = "leaves-be-gone"

[[mods]]
type = "modrinth"
id = "just-mob-heads"

[[mods]]
type = "modrinth"
id = "just-player-heads"

[[mods]]
type = "modrinth"
id = "monsters-in-the-closet"

[[mods]]
type = "modrinth"
id = "tabtps"

[[mods]]
type = "modrinth"
id = "view-distance-fix"

[[mods]]
type = "modrinth"
id = "ante"

[[mods]]
type = "modrinth"
id = "nowballs-freeze-mobs"

[[mods]]
type = "modrinth"
id = "thorny-bush-protection"

## Worldgen
[[mods]]
type = "modrinth"
id = "snow-under-trees-remastered"

[[mods]]
type = "modrinth"
id = "dungeons-and-taverns"

[[mods]]
type = "modrinth"
id = "terralith"

[[mods]]
type = "modrinth"
id = "tectonic"

[[mods]]
type = "modrinth"
id = "nullscape"

[[mods]]
type = "modrinth"
id = "scorched"

[[mods]]
type = "modrinth"
id = "hopo-better-underwater-ruins"

## Anti-cheats
[[mods]]
type = "modrinth"
id = "anti-xray"

[variables]
SERVER_PORT = "25565"
MOTD = "Aber!"

[launcher]
eula_args = true

[markdown]
files = ["README.md"]
auto_update = true

[options]
success_line = ""
stop_command = ""
