name = "mc-server"
mc_version = "1.21.3"

[jar]
type = "fabric"
loader = "latest"
installer = "latest"

# Mods

## Base/Libraries
[[mods]]
type = "modrinth"
id = "fabric-api"


## Optimization/Stability

## Admin tools

## Technical/Networking

## Commands

## Gamplay/Features

## Worldgen

## Anti-cheats

[variables]
SERVER_PORT = "25565"
MOTD = "Aber!"

[launcher]
eula_args = true

[markdown]
files = ["README.md"]
auto_update = true

[options]
success_line = ""
stop_command = ""
